### PR TITLE
chore: cibuildwheel is now part of the pypa

### PR DESCRIPTION
**Pull request by henryiii**
Be sure to checkout cibuildwheel 2.0's new config options when it comes out; you can set static values in your pyproject.toml file in 2.0!

### CODE REVIEW

**Comment by maxbachmann** [comment]
Thanks for updating the workflow.

Do you happen to know a different project using cibuildwheel which uses OpenMP and successfully builds wheels for mac os (preferably using github actions). I would like to add support for multi threading to the package, but I failed to build the mac os wheels.

**Comment by henryiii** [comment]
I'd add brew install libomp, then link to the so it provides, and then rely on delocate to bundle it, I think. See https://iscinumpy.gitlab.io/post/omp-on-high-sierra/ for the flags you'd need.

**Comment by henryiii** [comment]
Otherwise, not sure of who's doing it, I'd start with https://cibuildwheel.readthedocs.io/en/stable/working-examples/ - looking at that, I'd say https://github.com/EdoPro98/SimSiPM - but I don't see any openmp usage in the cibuildwheel file, just the setup.py.

**Comment by maxbachmann** [comment]
> I'd add brew install libomp

Thanks! I previously tried using `brew install openmp` which did not work. Using `brew install libomp` it compiles fine :tada:

> I'd say https://github.com/EdoPro98/SimSiPM 

I did look into this project previously, since it is listed as a project using openmp in the cibuildwheel Readme. However it only builds a version without openmp using cibuildwheel.

**Comment by henryiii** [comment]
Happy to add RapidFuzzto the list with 'macOS OpenMP' in the notes if you get it going. :)

**Comment by maxbachmann** [comment]
@henryiii Do you have an idea, how this can be achieved when cross compiling for Universal2/ARM64?

**Comment by henryiii** [comment]
Ouch. You'd need to figure out how to get the ARM package for libomp from brew on an Intel system, and you'd have to use that one for the Arm64 version. I don't know how to get brew to do this.

You probably could merge the two into a Universal2 lib (not sure how to do that), then you'd be able to do the "universal" wheel. It's possible to do the merge after building the wheels, but cibuildwheel doesn't have a built-in way to do that, though I'd assume you could do it after cibuildwheel runs (there's an issue open for adding a shortcut for that).

**Pull request merged**
