### PR TITLE
fix: pypy

### PR DESCRIPTION
**Pull request by henryiii**
Tiny removal that should no longer be needed. Also loosening the scikit-build pin just a tiny bit, allowing future patch releases if there are any.

### CODE REVIEW

**Comment by henryiii** [comment]
This is just the FindPython changes now + main scikit-build. Can you see if it builds?

**Comment by maxbachmann** [comment]
This repo has jarowinkler has dependency which has the same build issues. Could you create the PR over there: https://github.com/maxbachmann/JaroWinkler?
It has the same project structure and only a single module, so it should be relatively simple to apply the changes there

**Comment by maxbachmann** [comment]
This makes the CI finish a lot faster as well :)

**Comment by maxbachmann** [comment]
It looks like this is the same I already applied here: https://github.com/maxbachmann/JaroWinkler/pull/11/
which did find PyPy, but failed to name + install the so file.

**Comment by maxbachmann** [comment]
wow first time seeing this failure https://github.com/maxbachmann/RapidFuzz/actions/runs/3100994873/jobs/5022090041 not quite sure what went wrong there ...
Note this is on the current main branch, so without the changes from here

**Comment by maxbachmann** [comment]
I am currently pretty strict with the versions, since the last releases often broke things and I release new versions more regularly than `scikit-build`. However allowing further patch releases should be fine. This needs the same change in `tools/sdist.patch` to work.

**Pull request merged**
