### PR TITLE
Read the Docs Setup

### PR DESCRIPTION
**Pull request by TrigonaMinima**
Creating a pull for the Read the Docs setup and starting documentation. This PR is towards the issue #17.

For more extensive documentation on functions we should add extensive docstrings in each of the functions. Then the main file can be changed to pull those docstrings from the code.

### CODE REVIEW

**Comment by maxbachmann** [comment]
Thanks. I will look into this later this week :)

**Comment by maxbachmann** [comment]
I would prefer using mkdocs instead of sphinx (simply because I use markdown in most of my documentations already)

**Comment by TrigonaMinima** [comment]
Cool. Will change to mkdocs this weekend. In the mean time, i guess adding docstrings to the functions should help.

**Comment by maxbachmann** [comment]
Most functions (fuzz.*, process.*) already have docstring. Currently they include one sentence about what the functions does, a description of the arguments the ones that have an example in the readme have an example in the docstring aswell. Is there anything in particular your missing in them to make them more helpful?

**Comment by TrigonaMinima** [comment]
Oh i didn't check the code actually. When I tried to pull the docstring using sphinx, nothing came, so i thought there's no docstrings. Apologies. Will see what's happening this weekend.

**Comment by maxbachmann** [comment]
The docstrings of rapidfuzz.fuzz can now be found here: https://github.com/maxbachmann/rapidfuzz/blob/master/src/py_fuzz.cpp

I will create some flow charts that show which matching algorithms are used in them aswell

**Comment by maxbachmann** [comment]
I started to generate the docs for the c++ version aswell: https://maxbachmann.github.io/rapidfuzz-cpp/modules.html

**Comment by maxbachmann** [comment]
@TrigonaMinima do you already know when you have time to convert this to mkdocs?

**Comment by TrigonaMinima** [comment]
So, I looked into it. I have added the basic pages, but turns out, mkdocs won't read through the source files to load the docstrings. All the documentation will have to be added manually.

**Comment by TrigonaMinima** [comment]
There's some plugin, looking into how it works out for us. Will update here.

**Comment by TrigonaMinima** [comment]
This contains the list of plugins: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building. 2-3 are statics site generators which create a site folder or something like that. `mkdocstrings` works nicely with fuzz.py but fails for process.py - can't figure out why. It also requires the use of a particular file.

I think, sphinx is better tool. All major projects - pandas, scikit, numpy - use sphinx. It's your call. I'll push the changes I made to make it work with mkdocs. Let me know.

**Comment by maxbachmann** [comment]
Hm yes when it does not work automatically with mkdocs, but does with sphinx I think using sphinx is better suited for the job. Does sphinx retrieve them from the files, or from the library?
Since calling python functions is incredibly slow rapidfuzz.fuzz (fuzz.py got removed), rapidfuzz.levenshtein and rapdifuzz.utils are directly implemented in C++ and therefore the docstrings can only be found in the C++ files

Edit: Seems like https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html is importing them

**Comment by TrigonaMinima** [comment]
So how do you wanna proceed?

**Comment by maxbachmann** [comment]
We can go with sphinx. Do you know how to automatically generate the docs with autodocs? I did not use it before myself

**Comment by TrigonaMinima** [comment]
Awesome. How did you make it work?

**Comment by TrigonaMinima** [comment]
Ahh. So parameters description and docstrings are still not there. We have to make that part work. I was stuck on that.

**Comment by maxbachmann** [comment]
I decided that I will manually port them over for two reasons:
1) I would like to be able to write longer explanations in the documentation, than I could in the docstrings
2) there are versions of rapidfuzz for other programming languages. Currently C++ and Python, but I will probably add a rust version aswell. So I would like to have one documentation for all of them together -> I figured it would be a pain to automate this

https://maxbachmann.github.io/rapidfuzz/usage/ currently only includes the simple examples from the docstrings for Python and C++, so Parameter descriptions still have to be added.

**Comment by TrigonaMinima** [comment]
Yeah, fair. It'll be difficult to maintain documentation for multiple versions of the lib, but if we are only going to support the latest then there won't be any issues with manual documentation.

**Pull request merged**
