### PR TITLE
added check test submodule tags

### PR DESCRIPTION
**Pull request by kzelias**
added check test submodule tags
https://github.com/maxbachmann/RapidFuzz/issues/245

### CODE REVIEW

**Comment by maxbachmann** [comment]
Thanks for working on this

**Comment by maxbachmann** [comment]
Tests in rapidfuzz are not only used by people developing the library, but by a lot of downstream users as well (e.g. when packaging for Linux distributions). I think it would make more sense to place this inside tools and run it separately in the CI.

My long term vision for this is to have some sort of pre-release-validation tool. This tool could do the following:
- validate submodules
  - extern/rapidfuzz-cpp should point to the latest available tag
  - extern/Taskflow should point to a tag (not necessarily the latest)
- check the version number in the sources (e.g. in setup.py) matches the one in the git tag of the current release run
- check if the latest changelog entry matches the version number and has an associated date

In addition it could provide a mode to run these steps for the user.

**Comment by mikegerber** [comment]
>     * check the version number in the sources (e.g. in setup.py) matches the one in the git tag of the current release run

(Just stumbled upon this PR while looking for RapidFuzz 3)

Maybe this helps: https://github.com/qurator-spk/dinglehopper/blob/master/.github/workflows/release-check-version-tag

We use this before building a wheel in the release workflow; it may even be simpler to read the version after you have a wheel ready. You may want to add `--exact-match` to the `git describe` tag but I don't remember the exact details here.

**Comment by maxbachmann** [comment]
https://github.com/maxbachmann/RapidFuzz/commit/7822e014696317f0e4e0a7f09793b41075662e5b adds the submodule version check based on this PR.

The other version checks will be added separately. Thanks @mikegerber for pointing me to your solution.

**Pull request closed without merging**
