### PR TITLE
Add explanation of different output with fuzzywuzzy

### PR DESCRIPTION
**Pull request by cktang88**
I gave it a go at trying to explain to newcomers why it's different, cobbled together from several explanations across different issues. 

@maxbachmann , feel free to edit/clarify/add however you like, thanks! :)

### CODE REVIEW

**Comment by maxbachmann** [comment]
Wow that was fast :)
I think it would make sense to format this in the same way as the failure explanation `failure "ImportError: DLL load failed"` which is already in the readme.

**Comment by cktang88** [comment]
done!

**Comment by maxbachmann** [comment]
Thanks. This looks good now.
Would you like to squash the commits, or should I do this when merging?

**Comment by cktang88** [comment]
Squashing when merging is probably easier I think, thanks.

**Pull request merged**
