### PR TITLE
fix: correction for known wheels

### PR DESCRIPTION
**Pull request by henryiii**
Just noticed this when working on scikit-build-core.

### CODE REVIEW

**Comment by maxbachmann** [comment]
thanks. Do you already know when scikit-build-core 0.10.0 will be released? I think it should now contain everything required to migrate my libraries.

**Comment by henryiii** [comment]
Remaining is here: https://github.com/scikit-build/scikit-build-core/milestone/3

It will be out before our next community meeting for sure (third Friday), and before our next developer meeting (first Friday) is a stretch goal, but I think we might make it.

If you could test with a development version, I can make a dev release if that makes it easier, that would be helpful just in case there’s something missing. ;)

**Comment by maxbachmann** [comment]
I made a first attempt in https://github.com/rapidfuzz/RapidFuzz/commit/e43378ec6c3ceca5577d85d27bfd9363d8aec2e1

How would I specify multiple overrides? Right now this fails with `pip._vendor.tomli.TOMLDecodeError: Cannot declare ('tool', 'scikit-build', 'overrides') twice (at line 66, column 29)`

**Comment by maxbachmann** [comment]
Edit: read it again and I forgot braces ...

**Pull request merged**
